### ISSUE TITLE
KeyError when preprocessing for the training data

### ISSUE THREAD

**Issue by yichao-liang** [mdtux89/amr-eager#14]
When I try to preprocess the data for the training using the `smatch_old` in `amrevaluation` it generates this KeyError that I don't know why? The first line is the command I executed. (the printed 'i', 'segment',... is what I'm trying to debug with.)

`(amr) /disk/ocean/yichao-liang/amr-eager$ python preprocessing.py --amrs -f LDC2020T02/train/train_amr.txt`
```
<class 'amrevaluation.smatch_old.amr_edited.AMR'>
('i', 2)
('segment', '0.0')
('indexes', {'0.3.1': 'p', '0.1': 'd2', '0.0': 'm2', '0.3': 'a', '0.2': 't2', '0': 'm', '0.2.0': 'y2', '0.1.0': 'y', '0.3.0': 'i'})
('i', 6)
('segment', '0.0.0')
('indexes', {'0.3.1': 'p', '0.1': 'd2', '0.0': 'm2', '0.3': 'a', '0.2': 't2', '0': 'm', '0.2.0': 'y2', '0.1.0': 'y', '0.3.0': 'i'})
Traceback (most recent call last):
  File "preprocessing.py", line 157, in <module>
    run(args.file, args.amrs)
  File "preprocessing.py", line 32, in run
    data = AMRDataset(prefix, amrs)
  File "/disk/ocean/yichao-liang/amr-eager/amrdata.py", line 49, in __init__
    a = Alignments(prefix + ".alignments", allgraphs)
  File "/disk/ocean/yichao-liang/amr-eager/alignments.py", line 71, in __init__
    al[i].append(indexes[segment])
KeyError: '0.0.0'
```

**Comment by yichao-liang** [comment]
I've also tried the new smatch module from amrevaluation, in that case it would throw this no attribute 'get_triples3' error.

```<class 'amrevaluation.smatch.amr.AMR'>
Traceback (most recent call last):
  File "preprocessing.py", line 157, in <module>
    run(args.file, args.amrs)
  File "preprocessing.py", line 32, in run
    data = AMRDataset(prefix, amrs)
  File "/disk/ocean/yichao-liang/amr-eager/amrdata.py", line 49, in __init__
    a = Alignments(prefix + ".alignments", allgraphs)
  File "/disk/ocean/yichao-liang/amr-eager/alignments.py", line 56, in __init__
    indexes = self._traverse(parsed_amr, amr)
  File "/disk/ocean/yichao-liang/amr-eager/alignments.py", line 20, in _traverse
    triples = parsed_amr.get_triples3()
AttributeError: 'AMR' object has no attribute 'get_triples3'
```

**Comment by mdtux89** [comment]
Do you get the same problems with  https://github.com/mdtux89/amr-eager-multilingual?

**Comment by yichao-liang** [comment]
I'll double check, but I was thinking to first get some scores with the mono-lingual one first.

**Comment by mdtux89** [comment]
Thanks

**Comment by yichao-liang** [comment]
Thanks it worked!
