### ISSUE TITLE
.parsed file is empty!

### ISSUE THREAD

**Issue by JunhyunB** [mdtux89/amr-eager#8]
**$ ./preprocessing.sh -s contrib/sample-sentences.txt** 
Running CoreNLP..
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.6 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [1.2 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [0.5 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.7 sec].
[main] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
Exception in thread "main" edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingException: Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl
	at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLoading.java:40)
	at edu.stanford.nlp.time.TimeExpressionExtractorFactory.create(TimeExpressionExtractorFactory.java:57)
	at edu.stanford.nlp.time.TimeExpressionExtractorFactory.createExtractor(TimeExpressionExtractorFactory.java:38)
	at edu.stanford.nlp.ie.regexp.NumberSequenceClassifier.<init>(NumberSequenceClassifier.java:82)
	at edu.stanford.nlp.ie.NERClassifierCombiner.<init>(NERClassifierCombiner.java:85)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.ner(AnnotatorImplementations.java:108)
	at edu.stanford.nlp.pipeline.AnnotatorFactories$6.create(AnnotatorFactories.java:333)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:85)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:375)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:139)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:135)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.main(StanfordCoreNLP.java:1222)
Caused by: edu.stanford.nlp.util.MetaClass$ClassCreationException: MetaClass couldn't create public edu.stanford.nlp.time.TimeExpressionExtractorImpl(java.lang.String,java.util.Properties) with args [sutime, {}]
	at edu.stanford.nlp.util.MetaClass$ClassFactory.createInstance(MetaClass.java:235)
	at edu.stanford.nlp.util.MetaClass.createInstance(MetaClass.java:380)
	at edu.stanford.nlp.util.ReflectionLoading.loadByReflection(ReflectionLoading.java:38)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at edu.stanford.nlp.util.MetaClass$ClassFactory.createInstance(MetaClass.java:231)
	... 13 more
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at de.jollyday.util.CalendarUtil.<init>(CalendarUtil.java:42)
	at de.jollyday.HolidayManager.<init>(HolidayManager.java:73)
	at de.jollyday.impl.XMLManager.<init>(XMLManager.java:52)
	at edu.stanford.nlp.time.JollyDayHolidays$MyXMLManager.<init>(JollyDayHolidays.java:153)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.lang.Class.newInstance(Class.java:560)
	at de.jollyday.HolidayManager.instantiateManagerImpl(HolidayManager.java:255)
	at de.jollyday.HolidayManager.createManager(HolidayManager.java:276)
	at de.jollyday.HolidayManager.getInstance(HolidayManager.java:194)
	at edu.stanford.nlp.time.JollyDayHolidays.init(JollyDayHolidays.java:55)
	at edu.stanford.nlp.time.Options.<init>(Options.java:90)
	at edu.stanford.nlp.time.TimeExpressionExtractorImpl.init(TimeExpressionExtractorImpl.java:45)
	at edu.stanford.nlp.time.TimeExpressionExtractorImpl.<init>(TimeExpressionExtractorImpl.java:39)
	... 18 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 34 more
Done!
**$ python preprocessing.py -f contrib/sample-sentences.txt**
**$ python parser.py -f contrib/sample-sentences.txt**
Writing file contrib/sample-sentences.txt.parsed ...

I tried but .parsed file is empty, 0 byte.

What should I do?

**Comment by mdtux89** [comment]
Hi, did you specify the correct path in preprocessing.sh? See https://github.com/mdtux89/amr-eager/issues/6. I'll update the readme to clarify this step.

**Comment by JunhyunB** [comment]
Yes, I believe my JAMR path is correct.
I don't have #6 error 'No such File' but empty .parsed file without terminal errors..

**Comment by mdtux89** [comment]
Right, sorry. It seems like it crashes while CoreNLP is parsing. It works fine for me. When you ran download.sh, did you get any errors while downloading corenlp? Can you check whether it installed it correctly? It should have created a 'stanford-corenlp-full-2015-12-09' directory containing corenlp.

**Comment by JunhyunB** [comment]
In amr-eager directory, there is 'stanford-corenlp-full-2015-12-09' folder and files in there. 
Could it be a problem with macOS??

**Comment by mdtux89** [comment]
I did have problems with mac, but usually at a later stage. Do you have the right version of Java? If you have access to a Linux machine, can you try with it? You can also try with the multilingual version of the parser (https://github.com/mdtux89/amr-eager-multilingual), but you are likely to have the same issue.

**Comment by JunhyunB** [comment]
Thanks a lot! I'll try with other OS..

**Comment by cuevasclemente** [comment]
Hi I am also having this problem when trying to run the preprocessing script. I'm on linux using Java 8,a nd I've installed the JAMR parser and the path seems right, furthermore the block where the config.sh script is sourced is being executed. Here's my stack trace:
```
➜ ./preprocessing.sh -s sentences.txt 
sourcing ./submodules/jamr/scripts/config.sh
Invalid range "\x{0CE6}-\x{0BEF}" in transliteration operator at cdec-master/corpus/support/quote-norm.pl line 149.
Running CoreNLP..
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0,5 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [1,4 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [0,8 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0,4 sec].
[main] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/defs.sutime.txt
juin 03, 2019 4:17:25 PM edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules
INFOS: Read 83 rules
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/english.sutime.txt
juin 03, 2019 4:17:25 PM edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules
INFOS: Read 267 rules
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/english.holidays.sutime.txt
juin 03, 2019 4:17:25 PM edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules
INFOS: Read 25 rules
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
[main] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ...
done [0,4 sec].

Processing file /home/clemente/src/github.com/mdtux89/amr-eager/sentences.txt.sentences ... writing to /home/clemente/src/github.com/mdtux89/amr-eager/sentences.txt.out
Annotating file /home/clemente/src/github.com/mdtux89/amr-eager/sentences.txt.sentences
done.
Annotation pipeline timing information:
TokenizerAnnotator: 0,0 sec.
WordsToSentencesAnnotator: 0,0 sec.
POSTaggerAnnotator: 0,0 sec.
MorphaAnnotator: 0,0 sec.
NERCombinerAnnotator: 0,0 sec.
ParserAnnotator: 0,0 sec.
TOTAL: 0,0 sec. for 0 tokens at 0,0 tokens/sec.
Pipeline setup: 4,1 sec.
Total time for StanfordCoreNLP pipeline: 4,2 sec.
Done!

➜ cat sentences.txt
Bush claimed victory .
Hillary Clinton participated in the elections .
Mickey Mouse won the war .
The army refused to participate .

➜ cat sentences.txt.out

```

**Comment by mdtux89** [comment]
Hi Clemente, this seems to be a different issue altogether. I'm guessing CoreNLP crashes because of the 'Invalid range" error. Do you know what sentence causes it?

**Comment by cuevasclemente** [comment]
Hey, sorry, maybe I should have made another issue then. I don't know how to introspect what's going on in order to determine which sentence is causing the issue.

**Comment by cuevasclemente** [comment]
I was not able to get any sentences to work after selectively choosing some sentences from my `sentences.txt`

**Comment by mdtux89** [comment]
Can you try running the tokenizer on its own: cdec-master/corpus/tokenize-anything.sh < input_file and see if you get the same error? 

You may also want to try raising an issue at the tokenizer github page https://github.com/redpony/cdec/blob/master/corpus/tokenize-anything.sh. I never had any problem with the tokenizer and it seems odd that you cannot tokenize any sentences.

**Comment by cuevasclemente** [comment]
I think I temporarily resolved it. The line referenced in the file which seems to be converting urdu numerals to arabic numerals seems to not function on my machine and I'm not sure exactly what the reason could be. I'm guessing from your github avatar that you use Arch as well so I don't think it could be from my version of Perl being too recent. Either way I think I will be able to keep experimenting with this tool, thanks for your help!
