### ISSUE TITLE
Is this macOS problem?

### ISSUE THREAD

**Issue by JunhyunB** [mdtux89/amr-eager#9]
Writing file contrib/sample-sentences.txt.parsed ...
Sentence 1: Chapter 1 .
Warning: Failed to load function from bytecode: binary string: bad header in precompiled chunkTraceback (most recent call last):
  File "parser.py", line 164, in <module>
    main(args)
  File "parser.py", line 103, in main
    t = TransitionSystem(embs, data, "PARSE", args.model)
  File "/Users/junhyun/amr-eager/transition_system.py", line 35, in __init__
    self._classify = Classify(model_dir)
  File "/Users/junhyun/.local/lib/python3.6/site-packages/PyTorch-4.1.1_SNAPSHOT-py3.6-macosx-10.7-x86_64.egg/PyTorchHelpers.py", line 20, in __init__
    PyTorchAug.LuaClass.__init__(self, splitName, *args)
  File "/Users/junhyun/.local/lib/python3.6/site-packages/PyTorch-4.1.1_SNAPSHOT-py3.6-macosx-10.7-x86_64.egg/PyTorchAug.py", line 255, in __init__
    raise Exception(errorMessage)
Exception: ...s/junhyun/torch/install/share/lua/5.1/torch/File.lua:314: bad argument #1 to 'setupvalue' (function expected, got nil)

**Comment by mdtux89** [comment]
It's possible. It looks like it could be an architecture or lua/torch version issue. Can you try again with a Linux machine?

**Comment by JunhyunB** [comment]
I don't have Ubuntu machine, so I tried with Windows bash Ubuntu 18 and
there was some issues with install PyTorch

I really want to run with my MacBook but.. it seems that there is no solution..

**Comment by dariocazzani** [comment]
You might want to try to run a Docker Container or a VM running Linux on your Mac
